ENG-415
entando/entando-components pull request #696
Opened 2020-07-24 08:22 UTC by firegloves

- updated component usage logic for ContentTemplate, ContentType -> now if the requested resource is not present a usage count of 0 is returned instead of throwing a ResourceNotFoundException
- test update

2020-07-24 09:35 UTC, entando-service commented
All is Well

2020-07-24 19:50 UTC, ffleandro requested changes
I think it needs at least some integration tests.

2020-07-27 10:54 UTC, entando-service commented
All is Well

2020-07-27 13:56 UTC, ffleandro approved these changes

2020-07-27 13:57 UTC, merged